name: schedule-actions
on: 
  schedule:
    - cron: 15 4,12,20 * * *
jobs:
  build-job:
    runs-on: ubuntu-20.4
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: npm run schedule-action
